### ISSUE TITLE
Customer Search Bug

### ISSUE THREAD

**Issue by jdinick** [fortifi/issues#1]
Hey,

When filtering customers, instead of there being a true/false dropdown for the 'Has Purchased' filter, this only seems to work using 1 or 0 

![image](https://cloud.githubusercontent.com/assets/13832209/9303920/af86cd1e-44da-11e5-9195-be98117bd688.png)

**Comment by TomK** [comment]
@Jleagle please check other boolean definitions too

**Comment by Jleagle** [comment]
This is done, will be fixed on next deployment.
