### ISSUE TITLE
Customer Attribute Filters Not Showing Correctly (Messenger)

### ISSUE THREAD

**Issue by jdinick** [fortifi/issues#2]
I'm trying to set up a messenger campaign which targets users who have submitted the form to get a free consultation but not paid anything.

I have configured these filters in the setting section of the list, and they are reflecting in the list details:

![image](https://cloud.githubusercontent.com/assets/13832209/9379949/c6ef2342-4724-11e5-9c1f-7ec4188fce6c.png)

This appears to work, but when I go into /attribute-filters I still see true for both parameters:

![image](https://cloud.githubusercontent.com/assets/13832209/9379966/e0154af4-4724-11e5-9591-59f72a490888.png)

When you change has purchased to false and save it says filters saved (and reflects this in the details as it should) but then reverts back to true when you next load the /attribute-filters page.

**Comment by TomK** [comment]
Closed by https://github.com/fortifi/ui/commit/2617e1fa097ef57396c0eea11db9c9d9ca83c003

**Comment by TomK** [comment]
This will be fixed when we next deploy
