### ISSUE TITLE
Transaction Report Filtering / Search Stop Working

### ISSUE THREAD

**Issue by joekew** [fortifi/issues#26]
Transaction Report Filtering / Search Stopped Working

See below: 

https://backup.fortifi.it/marketing/reports/breakdown/id?action[]=acquisition&dateStart=2015-10-06&dateEnd=2015-10-06&advancedFilter=W3sia2V5IjoiZm91bmRhdGlvbkZpZCIsImNvbXBhcmF0b3IiOiJlcSIsInZhbHVlIjoiRklEOkFGRjpGTkROOjE0MzMxNTQ0MDA6NjNhOWY0NTAifV0%3D

![issue_with_transaction_filtering](https://cloud.githubusercontent.com/assets/15014410/10479739/fceebbec-725d-11e5-83fc-1fc571dbef1b.JPG)

**Comment by seemly** [comment]
A fix has been put in place. Changes will be seen upon next deployment.
