### ISSUE TITLE
Highlight High CPA accounts 

### ISSUE THREAD

**Issue by joekew** [fortifi/issues#28]
Hi Guys, 

Can we please get some markings in the Fortifi report that highlight high CPA's, this will help us spot anything that needs attention on our overview affiliate reports. 

Would be ideal to have anything over $150 orange or anything over $200 red. 

We only need to highlight / have the CPA text change colour. 

Thanks,
Joe

**Comment by bajb** [comment]
You can configure your targets in:

System Configuration > Marketing > Targets

Thanks
