### ISSUE TITLE
{{recipient.phone.phone}} macro not pulling through phone number

### ISSUE THREAD

**Issue by jdinick** [fortifi/issues#4]
Hey,

I tried inputting {{recipient.phone.phone}} in order to pull through the phone number captured on the lead form in a mailer, but I couldn't get it to work

![image](https://cloud.githubusercontent.com/assets/13832209/9405533/619a9d2e-47f0-11e5-8e5d-286d0d74990b.png)

Could you instruct me on the correct tag?

Thanks,

**Comment by Jleagle** [comment]
I have added some more buttons, they will appear when we next deploy.

We are still working on making the phone one work, but the rest should be okay.

**Comment by jdinick** [comment]
Awesome, thanks James

How often do you deploy?


On Fri, Aug 21, 2015 at 6:14 PM, James Eagle <notifications@github.com>
wrote:

> I have added some more buttons, they will appear when we next deploy.
>
> We are still working on making the phone one work, but the rest should be
> okay.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fortifi/issues/issues/4#issuecomment-133498310>.
>



-- 

*Nick Jackson*
*JDI Group Marketing Manager*

*Email: *nick.jackson@justdevelop.it

*Skype: *JDINick

*Office: *+44-1489-885050

*LinkedIn: *www.linkedin.com/in/nickjacksonjdi
<https://mail.google.com/mail/u/0/www.linkedin.com/in/nickjacksonjdi>

**Comment by Jleagle** [comment]
Just every so often, we have displayed this morning though.

**Comment by jdinick** [comment]
Hi mate,

This still doesn't appear to be pulling in correctly:

![image](https://cloud.githubusercontent.com/assets/13832209/9437565/2806d436-4a4f-11e5-9a0b-028c1dd3277e.png)

I used the button to input this time (you can see that here - http://prime.fortifi.it/messenger/message/10/compose) but doesn't seem to be pulling in my number.

Thanks,
