### ISSUE TITLE
Changing display name of autoresponder in messenger - not saving

### ISSUE THREAD

**Issue by jdinick** [fortifi/issues#5]
Hey,

http://prime.fortifi.it/messenger/campaign/8/settings/details

![image](https://cloud.githubusercontent.com/assets/13832209/9732044/9ab41c3a-5618-11e5-8dca-32f1b3279035.png)

When changing the name of the auto responder in messenger, I click the tick icon but it doesn't save over. 

Thanks,

**Comment by Jleagle** [comment]
Thanks. Will be fixed on next deploy.
