### ISSUE TITLE
Displaying agent name on replied tickets.

### ISSUE THREAD

**Issue by jdidan** [fortifi/issues#6]
Hi,

When you view a ticket threat, you can't easily see what agent replied. 

The title of a reply the email address is repeated twice. Is it possible to have the agents name and then email address. 

Please see attached image. 
![capture](https://cloud.githubusercontent.com/assets/14943352/10251335/daa8aca8-6927-11e5-80ff-dee59ac3a3a5.JPG)

Thanks,
Dan

**Comment by TomK** [comment]
The agent name has now been added to a footer on each post.
